version: '2'
services:
  db:
    container_name: mbti-discord-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    image: postgres:14
    environment:
      TZ: Europe/Paris
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}